services:
  taskit:
    build: .
    container_name: taskit
    environment:
      TZ: America/Phoenix
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
